# Welcome to Jekyll!
#

# Site settings
title: Hospital Benítez
description: |
  Bienvenido al Hospital Benítez
  donde te brindaremos una buena atención<br> 
  totalmente gratuita 
owner: Delgado Benítez Carlos Alberto # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Carlos_DB24
  #github: 
  #linkedin-square: 
  facebook-official: https://facebook.com/carlos.delgadobenitez.9
  #google-plus-square: 
  email: /delgadobenitezcarlosd@gmail.com/
  #flickr:
  instagram: https://instagram.com/_xcaldb24x_/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
