# Welcome to Jekyll!
#

# Site settings
title: Hospittal García
description: |
  Bienvenido al Hospital García
  Donde nos encargamos de brindarte la mejor atencion para tu salud y bienestar<br>
  Estamos catalogados como uno de los mejores hospitales de la zona
owner: García Alonso Ailton Gamaliel # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter:
  #github: 
  #linkedin-square: 
  facebook-official: https://facebook.com/carlos.delgadobenitez.9
  #google-plus-square: 
  email: ailtongama238@gmail.com
  #flickr:
  instagram: 
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
